notifications:
  email:
    on_success: never
    on_failure: never
git:
  depth: 1
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env: ATOM_CHANNEL=stable APM_TEST_PACKAGES="" CHROME_DEVEL_SANDBOX=""
    - os: linux
      dist: trusty
      sudo: required
      language: cpp
      env: ATOM_CHANNEL=beta APM_TEST_PACKAGES="" CHROME_DEVEL_SANDBOX=""
    - os: osx
      language: objective-c
      env: ATOM_CHANNEL=stable APM_TEST_PACKAGES=""
    - os: osx
      language: objective-c
      env: ATOM_CHANNEL=beta APM_TEST_PACKAGES=""
addons:
  apt:
    packages:
    - build-essential
    - git
    - libgnome-keyring-dev
    - fakeroot
script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh && node node_modules/xo/cli.js'
